name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: install sdl2
      run: sudo apt-get install libsdl2-dev
    - name: install wasm pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
    - name: Build terminal
      working-directory: terminal-raytracer
      run: cargo build --verbose
    - name: Run terminal tests
      working-directory: terminal-raytracer
      run: cargo test --verbose
      
    - name: Build sdl2
      working-directory: sdl2-raytracer
      run: cargo build --verbose
    - name: Run sdl2 tests
      working-directory: sdl2-raytracer
      run: cargo test --verbose

    - name: wasm pack build
      working-directory: wasm-raytracer
      run: wasm-pack build
    - name: npm install
      working-directory: wasm-raytracer/www
      run: npm install
